segments = {
    "MSH": {
        "MSH-1": "Field Separator",
        "MSH-2": "Encoding Characters",
        "MSH-3": "Sending Application",
        "MSH-4": "Sending Facility",
        "MSH-5": "Receiving Application",
        "MSH-6": "Receiving Facility",
        "MSH-7": "Date/Time of Message",
        "MSH-8": "Security",
        "MSH-9": "Message Type",
        "MSH-10": "Message Control ID",
        "MSH-11": "Processing ID",
        "MSH-12": "Version ID"
    },
    "MSA": {
        "MSA-1": "Acknowledgment Code",
        "MSA-2": "Message Control ID",
        "MSA-3": "Text Message"
    },
    "ERR": {
        "ERR-1": "Error Code and Location",
        "ERR-2": "Error Location",
        "ERR-3": "HL7 Error Code",
        "ERR-4": "Severity",
        "ERR-5": "Application Error Code",
        "ERR-6": "Application Error Parameter",
        "ERR-7": "Diagnostic Information",
        "ERR-8": "User Message",
        "ERR-9": "Inform Person Indicator",
        "ERR-10": "Override Type",
        "ERR-11": "Override Reason Code",
        "ERR-12": "Help Desk Contact Point",
        "ERR-13": "Unknown Field",
        "ERR-14": "Unknown Field",
        "ERR-15": "Unknown Field"
    },
    "NTE": {
        "NTE-1": "Set ID - NTE",
        "NTE-2": "Source of Comment",
        "NTE-3": "Comment",
        "NTE-4": "Comment Type"
    },
    "SFT": {
        "SFT-1": "Software Vendor Organization",
        "SFT-2": "Software Certified Version or Release Number",
        "SFT-3": "Software Product Name",
        "SFT-4": "Software Binary ID",
        "SFT-5": "Software Product Information"
    },
    "EVN": {
        "EVN-1": "Event Type Code",
        "EVN-2": "Recorded Date/Time",
        "EVN-3": "Date/Time Planned Event",
        "EVN-4": "Event Reason Code",
        "EVN-5": "Operator ID",
        "EVN-6": "Event Occurred"
    },
    "AUT": {
        "AUT-1": "Authorizing Payor, Plan ID",
        "AUT-2": "Authorizing Payor, Company ID",
        "AUT-3": "Authorizing Payor, Company Name",
        "AUT-4": "Authorization Effective Date",
        "AUT-5": "Authorization Expiration Date",
        "AUT-6": "Authorization Identifier",
        "AUT-7": "Reimbursement Limit"
    },
    "PID": {
        "PID-1": "Set ID - PID",
        "PID-2": "Patient ID",
        "PID-3": "Patient Identifier List",
        "PID-4": "Alternate Patient ID - PID",
        "PID-5": "Patient Name",
        "PID-6": "Mother's Maiden Name",
        "PID-7": "Date/Time of Birth",
        "PID-8": "Administrative Sex",
        "PID-9": "Patient Alias",
        "PID-10": "Race",
        "PID-11": "Patient Address",
        "PID-12": "County Code",
        "PID-13": "Phone Number - Home",
        "PID-14": "Phone Number - Business",
        "PID-15": "Primary Language",
        "PID-16": "Marital Status",
        "PID-17": "Religion",
        "PID-18": "Patient Account Number",
        "PID-19": "SSN Number - Patient",
        "PID-20": "Driver's License Number - Patient",
        "PID-21": "Mother's Identifier",
        "PID-22": "Ethnic Group",
        "PID-23": "Birth Place",
        "PID-24": "Multiple Birth Indicator",
        "PID-25": "Birth Order",
        "PID-26": "Citizenship",
        "PID-27": "Veterans Military Status",
        "PID-28": "Nationality",
        "PID-29": "Patient Death Date and Time",
        "PID-30": "Patient Death Indicator"
    },
    "PD1": {
        "PD1-1": "Living Dependency",
        "PD1-2": "Living Arrangement",
        "PD1-3": "Patient Primary Facility",
        "PD1-4": "Patient Primary Care Provider Name & ID No.",
        "PD1-5": "Student Indicator",
        "PD1-6": "Handicap",
        "PD1-7": "Living Will Code",
        "PD1-8": "Organ Donor Code",
        "PD1-9": "Separate Bill",
        "PD1-10": "Duplicate Patient",
        "PD1-11": "Publicity Code",
        "PD1-12": "Protection Indicator"
    },
    "NK1": {
        "NK1-1": "Set ID - NK1",
        "NK1-2": "Name",
        "NK1-3": "Relationship",
        "NK1-4": "Address",
        "NK1-5": "Phone Number",
        "NK1-6": "Business Phone Number",
        "NK1-7": "Contact Role",
        "NK1-8": "Start Date",
        "NK1-9": "End Date",
        "NK1-10": "Next of Kin / Associated Parties Job Title",
        "NK1-11": "Next of Kin / Associated Parties Job Code/Class",
        "NK1-12": "Next of Kin / Associated Parties Employee Number"
    },
    "PV1": {
        "PV1-1": "Set ID - PV1",
        "PV1-2": "Patient Class",
        "PV1-3": "Assigned Patient Location",
        "PV1-4": "Admission Type",
        "PV1-5": "Preadmit Number",
        "PV1-6": "Prior Patient Location",
        "PV1-7": "Attending Doctor",
        "PV1-8": "Referring Doctor",
        "PV1-9": "Consulting Doctor",
        "PV1-10": "Hospital Service",
        "PV1-11": "Temporary Location",
        "PV1-12": "Preadmit Test Indicator",
        "PV1-13": "Re-admission Indicator",
        "PV1-14": "Admit Source",
        "PV1-15": "Ambulatory Status",
        "PV1-16": "VIP Indicator",
        "PV1-17": "Admitting Doctor",
        "PV1-18": "Patient Type",
        "PV1-19": "Visit Number",
        "PV1-20": "Financial Class",
        "PV1-21": "Charge Price Indicator",
        "PV1-22": "Courtesy Code",
        "PV1-23": "Credit Rating",
        "PV1-24": "Contract Code",
        "PV1-25": "Contract Effective Date",
        "PV1-26": "Contract Amount",
        "PV1-27": "Contract Period",
        "PV1-28": "Interest Code",
        "PV1-29": "Transfer to Bad Debt Code",
        "PV1-30": "Transfer to Bad Debt Date",
        "PV1-31": "Bad Debt Agency Code",
        "PV1-32": "Bad Debt Transfer Amount",
        "PV1-33": "Bad Debt Recovery Amount",
        "PV1-34": "Delete Account Indicator",
        "PV1-35": "Delete Account Date",
        "PV1-36": "Discharge Disposition",
        "PV1-37": "Discharged to Location",
        "PV1-38": "Diet Type",
        "PV1-39": "Servicing Facility",
        "PV1-40": "Bed Status",
        "PV1-41": "Account Status",
        "PV1-42": "Pending Location",
        "PV1-43": "Prior Temporary Location",
        "PV1-44": "Admit Date/Time",
        "PV1-45": "Discharge Date/Time",
        "PV1-46": "Current Patient Balance",
        "PV1-47": "Total Charges",
        "PV1-48": "Total Adjustments"
    },
    "PV2": {
        "PV2-1": "Prior Pending Location",
        "PV2-2": "Accommodation Code",
        "PV2-3": "Admit Reason",
        "PV2-4": "Transfer Reason",
        "PV2-5": "Patient Valuables",
        "PV2-6": "Patient Valuables Location",
        "PV2-7": "Visit User Code",
        "PV2-8": "Expected Admit Date/Time",
        "PV2-9": "Expected Discharge Date/Time",
        "PV2-10": "Estimated Length of Inpatient Stay",
        "PV2-11": "Actual Length of Inpatient Stay",
        "PV2-12": "Visit Description",
        "PV2-13": "Referral Source Code",
        "PV2-14": "Previous Service Date",
        "PV2-15": "Employment Illness Related Indicator",
        "PV2-16": "Purge Status Code",
        "PV2-17": "Purge Status Date",
        "PV2-18": "Special Program Code",
        "PV2-19": "Retention Indicator",
        "PV2-20": "Expected Number of Insurance Plans",
        "PV2-21": "Visit Publicity Code",
        "PV2-22": "Visit Protection Indicator",
        "PV2-23": "Clinic Organization Name",
        "PV2-24": "Patient Status Code",
        "PV2-25": "Visit Priority Code",
        "PV2-26": "Previous Treatment Date",
        "PV2-27": "Expected Discharge Disposition",
        "PV2-28": "Signature on File Date"
    },
    "ROL": {
        "ROL-1": "Role Instance ID",
        "ROL-2": "Action Code",
        "ROL-3": "Role-ROL",
        "ROL-4": "Role Person",
        "ROL-5": "Role Begin Date/Time",
        "ROL-6": "Role End Date/Time",
        "ROL-7": "Role Duration",
        "ROL-8": "Role Action Reason",
        "ROL-9": "Provider Type",
        "ROL-10": "Organization Unit Type",
        "ROL-11": "Office/Home Address/Birthplace",
        "ROL-12": "Phone",
        "ROL-13": "Person's Location",
        "ROL-14": "Organization"
    },
    "PDA": {
        "PDA-1": "Death Cause Code",
        "PDA-2": "Death Location",
        "PDA-3": "Death Certified Indicator",
        "PDA-4": "Death Certificate Signed Date/Time",
        "PDA-5": "Death Certified By",
        "PDA-6": "Autopsy Indicator",
        "PDA-7": "Autopsy Start and End Date/Time",
        "PDA-8": "Autopsy Performed By"
    },
    "ORC": {
        "ORC-1": "Order Control",
        "ORC-2": "Placer Order Number",
        "ORC-3": "Filler Order Number",
        "ORC-4": "Placer Group Number",
        "ORC-5": "Order Status",
        "ORC-6": "Response Flag",
        "ORC-7": "Quantity/Timing",
        "ORC-8": "Parent Order",
        "ORC-9": "Date/Time of Transaction",
        "ORC-10": "Entered By",
        "ORC-11": "Verified By",
        "ORC-12": "Ordering Provider",
        "ORC-13": "Enterer's Location",
        "ORC-14": "Call Back Phone Number",
        "ORC-15": "Order Effective Date/Time",
        "ORC-16": "Order Control Code Reason",
        "ORC-17": "Entering Organization",
        "ORC-18": "Entering Device",
        "ORC-19": "Action By",
        "ORC-20": "Advanced Beneficiary Notice Code",
        "ORC-21": "Ordering Facility Name"
    },
    "OBR": {
        "OBR-1": "Set ID - OBR",
        "OBR-2": "Placer Order Number",
        "OBR-3": "Filler Order Number",
        "OBR-4": "Universal Service Identifier",
        "OBR-5": "Priority",
        "OBR-6": "Requested Date/Time",
        "OBR-7": "Observation Date/Time #",
        "OBR-8": "Observation End Date/Time #",
        "OBR-9": "Collection Volume *",
        "OBR-10": "Collector Identifier *",
        "OBR-11": "Specimen Action Code *",
        "OBR-12": "Danger Code",
        "OBR-13": "Relevant Clinical Information",
        "OBR-14": "Specimen Received Date/Time",
        "OBR-15": "Specimen Source",
        "OBR-16": "Ordering Provider",
        "OBR-17": "Order Callback Phone Number",
        "OBR-18": "Placer Field 1",
        "OBR-19": "Placer Field 2",
        "OBR-20": "Filler Field 1 +",
        "OBR-21": "Filler Field 2 +",
        "OBR-22": "Results Rpt/Status Chng - Date/Time +",
        "OBR-23": "Charge to Practice +",
        "OBR-24": "Diagnostic Serv Sect ID",
        "OBR-25": "Result Status +",
        "OBR-26": "Parent Result +",
        "OBR-27": "Quantity/Timing",
        "OBR-28": "Result Copies To",
        "OBR-29": "Parent  Results Observation Identifier",
        "OBR-30": "Transportation Mode",
        "OBR-31": "Reason for Study",
        "OBR-32": "Principal Result Interpreter +",
        "OBR-33": "Assistant Result Interpreter +",
        "OBR-34": "Technician +",
        "OBR-35": "Transcriptionist +",
        "OBR-36": "Scheduled Date/Time +",
        "OBR-37": "Number of Sample Containers *",
        "OBR-38": "Transport Logistics of Collected Sample *",
        "OBR-39": "Collector's Comment *",
        "OBR-40": "Transport Arrangement Responsibility",
        "OBR-41": "Transport Arranged",
        "OBR-42": "Escort Required",
        "OBR-43": "Planned Patient Transport Comment",
        "OBR-44": "Procedure Code",
        "OBR-45": "Procedure Code Modifier",
        "OBR-46": "Placer Supplemental Service Information",
        "OBR-47": "Filler Supplemental Service Information",
        "OBR-48": "Medically Necessary Duplicate Procedure Reason"
    },
    "OBX": {
        "OBX-1": "Set ID - OBX",
        "OBX-2": "Value Type",
        "OBX-3": "Observation Identifier",
        "OBX-4": "Observation Sub-ID",
        "OBX-5": "Observation Value",
        "OBX-6": "Units",
        "OBX-7": "References Range",
        "OBX-8": "Interpretation Codes",
        "OBX-9": "Probability",
        "OBX-10": "Nature of Abnormal Test",
        "OBX-11": "Observation Result Status",
        "OBX-12": "Effective Date of Reference Range",
        "OBX-13": "User Defined Access Checks",
        "OBX-14": "Date/Time of the Observation",
        "OBX-15": "Producer's ID",
        "OBX-16": "Responsible Observer",
        "OBX-17": "Observation Method",
        "OBX-18": "Equipment Instance Identifier",
        "OBX-19": "Date/Time of the Analysis",
        "OBX-20": "Observation Site"
    },
    "SPM": {
        "SPM-1": "Set ID - SPM",
        "SPM-2": "Specimen ID",
        "SPM-3": "Specimen Parent IDs",
        "SPM-4": "Specimen Type",
        "SPM-5": "Specimen Type Modifier",
        "SPM-6": "Specimen Additives",
        "SPM-7": "Specimen Collection Method",
        "SPM-8": "Specimen Source Site",
        "SPM-9": "Specimen Source Site Modifier",
        "SPM-10": "Specimen Collection Site",
        "SPM-11": "Specimen Role",
        "SPM-12": "Specimen Collection Amount",
        "SPM-13": "Grouped Specimen Count",
        "SPM-14": "Specimen Description",
        "SPM-15": "Specimen Handling Code",
        "SPM-16": "Specimen Risk Code",
        "SPM-17": "Specimen Collection Date/Time",
        "SPM-18": "Specimen Received Date/Time",
        "SPM-19": "Specimen Expiration Date/Time",
        "SPM-20": "Specimen Availability",
        "SPM-21": "Specimen Reject Reason",
        "SPM-22": "Specimen Quality",
        "SPM-23": "Specimen Appropriateness",
        "SPM-24": "Specimen Condition",
        "SPM-25": "Specimen Current Quantity",
        "SPM-26": "Number of Specimen Containers"
    },
    "RXE": {
        "RXE-1": "Quantity/Timing",
        "RXE-2": "Give Code",
        "RXE-3": "Give Amount - Minimum",
        "RXE-4": "Give Amount - Maximum",
        "RXE-5": "Give Units",
        "RXE-6": "Give Dosage Form",
        "RXE-7": "Provider's Administration Instructions",
        "RXE-8": "Deliver-To Location",
        "RXE-9": "Substitution Status",
        "RXE-10": "Dispense Amount",
        "RXE-11": "Dispense Units",
        "RXE-12": "Number Of Refills",
        "RXE-13": "Ordering Provider's DEA Number",
        "RXE-14": "Pharmacist/Treatment Supplier's Verifier ID",
        "RXE-15": "Prescription Number",
        "RXE-16": "Number of Refills Remaining",
        "RXE-17": "Number of Refills/Doses Dispensed",
        "RXE-18": "D/T of Most Recent Refill or Dose Dispensed",
        "RXE-19": "Total Daily Dose",
        "RXE-20": "Needs Human Review",
        "RXE-21": "Special Dispensing Instructions",
        "RXE-22": "Give Per (Time Unit)",
        "RXE-23": "Give Rate Amount",
        "RXE-24": "Give Rate Units",
        "RXE-25": "Give Strength",
        "RXE-26": "Give Strength Units",
        "RXE-27": "Give Indication",
        "RXE-28": "Dispense Package Size"
    },
    "RXA": {
        "RXA-1": "Give Sub-ID Counter",
        "RXA-2": "Administration Sub-ID Counter",
        "RXA-3": "Date/Time Start of Administration",
        "RXA-4": "Date/Time End of Administration",
        "RXA-5": "Administered Code",
        "RXA-6": "Administered Amount",
        "RXA-7": "Administered Units",
        "RXA-8": "Administered Dosage Form",
        "RXA-9": "Administration Notes",
        "RXA-10": "Administering Provider",
        "RXA-11": "Administered-at Location",
        "RXA-12": "Administered Per (Time Unit)",
        "RXA-13": "Administered Strength",
        "RXA-14": "Administered Strength Units",
        "RXA-15": "Substance Lot Number",
        "RXA-16": "Substance Expiration Date",
        "RXA-17": "Substance Manufacturer Name",
        "RXA-18": "Substance/Treatment Refusal Reason",
        "RXA-19": "Indication",
        "RXA-20": "Completion Status",
        "RXA-21": "Action Code - RXA",
        "RXA-22": "System Entry Date/Time"
    },
    "RXR": {
        "RXR-1": "Route",
        "RXR-2": "Administration Site",
        "RXR-3": "Administration Device",
        "RXR-4": "Administration Method",
        "RXR-5": "Routing Instruction"
    },
    "RXC": {
        "RXC-1": "RX Component Type",
        "RXC-2": "Component Code",
        "RXC-3": "Component Amount",
        "RXC-4": "Component Units",
        "RXC-5": "Component Strength",
        "RXC-6": "Component Strength Units"
    },
    "FT1": {
        "FT1-1": "Set ID - FT1",
        "FT1-2": "Transaction ID",
        "FT1-3": "Transaction Batch ID",
        "FT1-4": "Transaction Date",
        "FT1-5": "Transaction Posting Date",
        "FT1-6": "Transaction Type",
        "FT1-7": "Transaction Code",
        "FT1-8": "Transaction Description",
        "FT1-9": "Transaction Description - Alt",
        "FT1-10": "Transaction Quantity",
        "FT1-11": "Transaction Amount - Extended",
        "FT1-12": "Transaction amount - unit",
        "FT1-13": "Department Code",
        "FT1-14": "Health Plan ID",
        "FT1-15": "Insurance Amount",
        "FT1-16": "Assigned Patient Location",
        "FT1-17": "Fee Schedule",
        "FT1-18": "Patient Type",
        "FT1-19": "Diagnosis Code - FT1",
        "FT1-20": "Performed By Code"
    },
    "IN1": {
        "IN1-1": "Set ID - IN1",
        "IN1-2": "Health Plan ID",
        "IN1-3": "Insurance Company ID",
        "IN1-4": "Insurance Company Name",
        "IN1-5": "Insurance Company Address",
        "IN1-6": "Insurance Co Contact Person",
        "IN1-7": "Insurance Co Phone Number",
        "IN1-8": "Group Number",
        "IN1-9": "Group Name",
        "IN1-10": "Insured's Group Emp ID",
        "IN1-11": "Insured's Group Emp Name",
        "IN1-12": "Plan Effective Date",
        "IN1-13": "Plan Expiration Date",
        "IN1-14": "Authorization Information",
        "IN1-15": "Plan Type",
        "IN1-16": "Name Of Insured",
        "IN1-17": "Insured's Relationship To Patient",
        "IN1-18": "Insured's Date Of Birth",
        "IN1-19": "Insured's Address",
        "IN1-20": "Assignment Of Benefits",
        "IN1-21": "Coordination Of Benefits",
        "IN1-22": "Coord Of Ben. Priority",
        "IN1-23": "Notice Of Admission Flag",
        "IN1-24": "Notice Of Admission Date",
        "IN1-25": "Report Of Eligibility Flag",
        "IN1-26": "Report Of Eligibility Date",
        "IN1-27": "Release Information Code",
        "IN1-28": "Pre-Admit Cert (PAC)",
        "IN1-29": "Verification Date/Time",
        "IN1-30": "Verification By",
        "IN1-31": "Type Of Agreement Code",
        "IN1-32": "Billing Status",
        "IN1-33": "Lifetime Reserve Days",
        "IN1-34": "Delay Before L.R. Day",
        "IN1-35": "Company Plan Code",
        "IN1-36": "Policy Number",
        "IN1-37": "Policy Deductible",
        "IN1-38": "Policy Limit - Amount",
        "IN1-39": "Policy Limit - Days",
        "IN1-40": "Room Rate - Semi-Private",
        "IN1-41": "Room Rate - Private",
        "IN1-42": "Insured's Employment Status",
        "IN1-43": "Insured's Administrative Sex",
        "IN1-44": "Insured's Employer's Address",
        "IN1-45": "Verification Status",
        "IN1-46": "Prior Insurance Plan ID",
        "IN1-47": "Coverage Type",
        "IN1-48": "Handicap",
        "IN1-49": "Insured's ID Number",
        "IN1-50": "Signature Code",
        "IN1-51": "Signature Code Date",
        "IN1-52": "Insured's Birth Place"
    },
    "IN2": {
        "IN2-1": "Insured's Employee ID",
        "IN2-2": "Insured's Social Security Number",
        "IN2-3": "Insured's Employer's Name and ID",
        "IN2-4": "Employer Information Data",
        "IN2-5": "Mail Claim Party",
        "IN2-6": "Medicare Health Ins Card Number",
        "IN2-7": "Medicaid Case Name",
        "IN2-8": "Medicaid Case Number",
        "IN2-9": "Military Sponsor Name",
        "IN2-10": "Military ID Number",
        "IN2-11": "Dependent Of Military Recipient",
        "IN2-12": "Military Organization",
        "IN2-13": "Military Station",
        "IN2-14": "Military Service",
        "IN2-15": "Military Rank/Grade",
        "IN2-16": "Military Status",
        "IN2-17": "Military Retire Date",
        "IN2-18": "Military Non-Avail Cert On File",
        "IN2-19": "Baby Coverage",
        "IN2-20": "Combine Baby Bill",
        "IN2-21": "Blood Deductible",
        "IN2-22": "Special Coverage Approval Name",
        "IN2-23": "Special Coverage Approval Title",
        "IN2-24": "Non-Covered Insurance Code",
        "IN2-25": "Payor ID",
        "IN2-26": "Payor Subscriber ID",
        "IN2-27": "Eligibility Source",
        "IN2-28": "Room Coverage Type/Amount",
        "IN2-29": "Policy Type/Amount",
        "IN2-30": "Daily Deductible",
        "IN2-31": "Living Dependency",
        "IN2-32": "Ambulatory Status",
        "IN2-33": "Citizenship",
        "IN2-34": "Primary Language",
        "IN2-35": "Living Arrangement",
        "IN2-36": "Publicity Code",
        "IN2-37": "Protection Indicator",
        "IN2-38": "Student Indicator",
        "IN2-39": "Religion",
        "IN2-40": "Mother's Maiden Name",
        "IN2-41": "Nationality",
        "IN2-42": "Ethnic Group",
        "IN2-43": "Marital Status",
        "IN2-44": "Insured's Employment Start Date",
        "IN2-45": "Employment Stop Date",
        "IN2-46": "Job Title",
        "IN2-47": "Job Code/Class",
        "IN2-48": "Job Status",
        "IN2-49": "Employer Contact Person Name",
        "IN2-50": "Employer Contact Person Phone Number",
        "IN2-51": "Employer Contact Reason",
        "IN2-52": "Insured's Contact Person's Name",
        "IN2-53": "Insured's Contact Person Phone Number",
        "IN2-54": "Insured's Contact Person Reason",
        "IN2-55": "Relationship to the Patient Start Date",
        "IN2-56": "Relationship to the Patient Stop Date",
        "IN2-57": "Insurance Co Contact Reason",
        "IN2-58": "Insurance Co Contact Phone Number",
        "IN2-59": "Policy Scope",
        "IN2-60": "Policy Source",
        "IN2-61": "Patient Member Number",
        "IN2-62": "Guarantor's Relationship to Insured"
    },
    "IN3": {
        "IN3-1": "Set ID - IN3",
        "IN3-2": "Certification Number",
        "IN3-3": "Certified By",
        "IN3-4": "Certification Required",
        "IN3-5": "Penalty",
        "IN3-6": "Certification Date/Time",
        "IN3-7": "Certification Modify Date/Time",
        "IN3-8": "Operator",
        "IN3-9": "Certification Begin Date",
        "IN3-10": "Certification End Date",
        "IN3-11": "Days",
        "IN3-12": "Non-Concur Code/Description",
        "IN3-13": "Non-Concur Effective Date/Time",
        "IN3-14": "Physician Reviewer",
        "IN3-15": "Certification Contact",
        "IN3-16": "Certification Contact Phone Number",
        "IN3-17": "Appeal Reason"
    },
    "SCH": {
        "SCH-1": "Placer Appointment ID",
        "SCH-2": "Filler Appointment ID",
        "SCH-3": "Occurrence Number",
        "SCH-4": "Placer Group Number",
        "SCH-5": "Schedule ID",
        "SCH-6": "Event Reason",
        "SCH-7": "Appointment Reason",
        "SCH-8": "Appointment Type",
        "SCH-9": "Appointment Duration",
        "SCH-10": "Appointment Duration Units",
        "SCH-11": "Appointment Timing Quantity",
        "SCH-12": "Placer Contact Person",
        "SCH-13": "Placer Contact Phone Number",
        "SCH-14": "Placer Contact Address",
        "SCH-15": "Placer Contact Location",
        "SCH-16": "Filler Contact Person"
    },
    "TQ1": {
        "TQ1-1": "Set ID - TQ1",
        "TQ1-2": "Quantity",
        "TQ1-3": "Repeat Pattern",
        "TQ1-4": "Explicit Time",
        "TQ1-5": "Relative Time and Units",
        "TQ1-6": "Service Duration",
        "TQ1-7": "Start date/time",
        "TQ1-8": "End date/time",
        "TQ1-9": "Priority",
        "TQ1-10": "Condition text"
    },
    "TQ2": {
        "TQ2-1": "Set ID - TQ2",
        "TQ2-2": "Sequence/Results Flag",
        "TQ2-3": "Related Placer Number",
        "TQ2-4": "Related Filler Number",
        "TQ2-5": "Related Placer Group Number",
        "TQ2-6": "Sequence Condition Code",
        "TQ2-7": "Cyclic Entry/Exit Indicator"
    },
    "PRD": {
        "PRD-1": "Provider Role",
        "PRD-2": "Provider Name",
        "PRD-3": "Provider Address",
        "PRD-4": "Provider Location",
        "PRD-5": "Provider Communication Information",
        "PRD-6": "Preferred Method of Contact",
        "PRD-7": "Provider Identifiers",
        "PRD-8": "Effective Start Date of Provider Role",
        "PRD-9": "Effective End Date of Provider Role",
        "PRD-10": "Provider Organization Name and Identifier",
        "PRD-11": "Provider Organization Address",
        "PRD-12": "Provider Organization Location Information",
        "PRD-13": "Provider Organization Communication Information",
        "PRD-14": "Provider Organization Method of Contact",
        "PRD-15": "Unknown Field"
    },
    "PRA": {
        "PRA-1": "Primary Key Value - PRA",
        "PRA-2": "Practitioner Group",
        "PRA-3": "Practitioner Category",
        "PRA-4": "Provider Billing",
        "PRA-5": "Specialty",
        "PRA-6": "Practitioner ID Numbers"
    },
    "MFI": {
        "MFI-1": "Master File Identifier",
        "MFI-2": "Master File Application Identifier",
        "MFI-3": "File-Level Event Code",
        "MFI-4": "Entered Date/Time",
        "MFI-5": "Effective Date/Time",
        "MFI-6": "Response Level Code"
    },
    "MFE": {
        "MFE-1": "Record-Level Event Code",
        "MFE-2": "MFN Control ID",
        "MFE-3": "Effective Date/Time",
        "MFE-4": "Primary Key Value - MFE",
        "MFE-5": "Primary Key Value Type",
        "MFE-6": "Entered Date/Time"
    },
    "AL1": {
        "AL1-1": "Set ID - AL1",
        "AL1-2": "Allergen Type Code",
        "AL1-3": "Allergen Code/Mnemonic/Description",
        "AL1-4": "Allergy Severity Code",
        "AL1-5": "Allergy Reaction Code",
        "AL1-6": "Identification Date"
    },
    "DG1": {
        "DG1-1": "Set ID - DG1",
        "DG1-2": "Diagnosis Coding Method",
        "DG1-3": "Diagnosis Code - DG1",
        "DG1-4": "Diagnosis Description",
        "DG1-5": "Diagnosis Date/Time",
        "DG1-6": "Diagnosis Type",
        "DG1-7": "Major Diagnostic Category",
        "DG1-8": "Diagnostic Related Group",
        "DG1-9": "DRG Approval Indicator",
        "DG1-10": "DRG Grouper Review Code",
        "DG1-11": "Outlier Type",
        "DG1-12": "Outlier Days",
        "DG1-13": "Outlier Cost",
        "DG1-14": "Grouper Version And Type",
        "DG1-15": "Diagnosis Priority"
    },
    "PR1": {
        "PR1-1": "Set ID - PR1",
        "PR1-2": "Procedure Coding Method",
        "PR1-3": "Procedure Code",
        "PR1-4": "Procedure Description",
        "PR1-5": "Procedure Date/Time",
        "PR1-6": "Procedure Functional Type",
        "PR1-7": "Procedure Minutes",
        "PR1-8": "Anesthesiologist",
        "PR1-9": "Anesthesia Code",
        "PR1-10": "Anesthesia Minutes",
        "PR1-11": "Surgeon",
        "PR1-12": "Procedure Practitioner",
        "PR1-13": "Consent Code",
        "PR1-14": "Procedure Priority",
        "PR1-15": "Associated Diagnosis Code",
        "PR1-16": "Procedure Code Modifier",
        "PR1-17": "Procedure DRG Type",
        "PR1-18": "Tissue Type Code",
        "PR1-19": "Procedure Identifier",
        "PR1-20": "Procedure Action Code"
    },
    "GT1": {
        "GT1-1": "Set ID - GT1",
        "GT1-2": "Guarantor Number",
        "GT1-3": "Guarantor Name",
        "GT1-4": "Guarantor Spouse Name",
        "GT1-5": "Guarantor Address",
        "GT1-6": "Guarantor Ph Num - Home",
        "GT1-7": "Guarantor Ph Num - Business",
        "GT1-8": "Guarantor Date/Time Of Birth",
        "GT1-9": "Guarantor Administrative Sex",
        "GT1-10": "Guarantor Type",
        "GT1-11": "Guarantor Relationship",
        "GT1-12": "Guarantor SSN",
        "GT1-13": "Guarantor Date - Begin",
        "GT1-14": "Guarantor Date - End",
        "GT1-15": "Guarantor Priority",
        "GT1-16": "Guarantor Employer Name",
        "GT1-17": "Guarantor Employer Address",
        "GT1-18": "Guarantor Employer Phone Number",
        "GT1-19": "Guarantor Employee ID Number",
        "GT1-20": "Guarantor Employment Status",
        "GT1-21": "Guarantor Organization Name",
        "GT1-22": "Guarantor Billing Hold Flag",
        "GT1-23": "Guarantor Credit Rating Code",
        "GT1-24": "Guarantor Death Date And Time",
        "GT1-25": "Guarantor Death Flag",
        "GT1-26": "Guarantor Charge Adjustment Code",
        "GT1-27": "Guarantor Household Annual Income",
        "GT1-28": "Guarantor Household Size",
        "GT1-29": "Guarantor Employer ID Number",
        "GT1-30": "Guarantor Marital Status Code",
        "GT1-31": "Guarantor Hire Effective Date",
        "GT1-32": "Employment Stop Date",
        "GT1-33": "Living Dependency",
        "GT1-34": "Ambulatory Status",
        "GT1-35": "Citizenship",
        "GT1-36": "Primary Language",
        "GT1-37": "Living Arrangement",
        "GT1-38": "Publicity Code",
        "GT1-39": "Protection Indicator",
        "GT1-40": "Student Indicator",
        "GT1-41": "Religion",
        "GT1-42": "Mother's Maiden Name",
        "GT1-43": "Nationality",
        "GT1-44": "Ethnic Group",
        "GT1-45": "Contact Person's Name",
        "GT1-46": "Contact Person's Telephone Number",
        "GT1-47": "Contact Reason",
        "GT1-48": "Contact Relationship",
        "GT1-49": "Job Title",
        "GT1-50": "Job Code/Class",
        "GT1-51": "Guarantor Employer's Organization Name",
        "GT1-52": "Handicap",
        "GT1-53": "Job Status",
        "GT1-54": "Guarantor Financial Class",
        "GT1-55": "Guarantor Race",
        "GT1-56": "Guarantor Birth Place",
        "GT1-57": "VIP Indicator",
        "GT1-58": "Unknown Field",
        "GT1-59": "Unknown Field",
        "GT1-60": "Unknown Field",
        "GT1-61": "Unknown Field"
    },
    'UB2': {
    "UB2-1": "Set ID - UB2",
    "UB2-2": "Co-Insurance Days (9)",
    "UB2-3": "Condition Code (24-30)",
    "UB2-4": "Covered Days (7)",
    "UB2-5": "Non-Covered Days (8)",
    "UB2-6": "Value Amount & Code (39-41)",
    "UB2-7": "Occurrence Code & Date (32-35)",
    "UB2-8": "Occurrence Span Code/Dates (36)",
    "UB2-9": "Uniform Billing Locator 2 (state)",
    "UB2-10": "Uniform Billing Locator 11 (state)",
    "UB2-11": "Uniform Billing Locator 31 (national)",
    "UB2-12": "Document Control Number",
    "UB2-13": "Uniform Billing Locator 49 (national)",
    "UB2-14": "Uniform Billing Locator 56 (state)",
    "UB2-15": "Uniform Billing Locator 57 (national)",
    "UB2-16": "Uniform Billing Locator 78 (state)",
    "UB2-17": "Special Visit Count"
    },

}

ignored_subfield_ids = ['PID-11.4', 'PID-5.7', 'PID-5.3', ]